### ISSUE TITLE
Add dark mode.

### ISSUE THREAD

**Issue by AmolKumarGupta** [AmolKumarGupta/givemecode#12]
dark mode for mobile and desktop

**Comment by SinaElahimanesh** [comment]
Hello AmolKumarGupta.
I have seen your issue [Issue #12 ](https://github.com/AmolKumarGupta/givemecode/issues/12).
So that I have added some pieces of javascript code at the bottom of your index.html file, which its task is to change the theme of your website to a dark theme. 
Also, I should mention that I have added a file (landing_dark.png) to your assets folder which is the dark theme of the background of the website. 
At last, I added some pieces of code in the CSS files, which is the dark theme of HTML components.
So please accept my Pull Request! :)

Thanks,
Sina
